name = "Astropunk"
author = "Lucas"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b72abf8f92e7e361a9c45615836e382871de6b0c0064a5edddcd9ad03ee1eb60"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.255"
