version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 1
includeMangroveRoots = true
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
seamlesssleep = true
farmersdelight = true
supplementaries = true
createbigcannons = true
create_factory = true
createprism = true
minersdelight = true
endrem = true
create = true
aeronautics = true
create_optical = true
simulated = true
quark = true
another_furniture = true
easyanvils = true
minecraft = true
lootr = true
ends_delight = true
sliceanddice = true
fastpaintings = true
railways = true
bellsandwhistles = true
bits_n_bobs = true
createframed = true
amendments = true
mynethersdelight = true
moonlight = true
alloyed = true
sophisticatedbackpacks = true
offroad = true
